// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALGmkHNr4R7meFSZio64T7JIwsaxyzDlk',
    appId: '1:104865530314:web:aab2bd9f8decc82c294f33',
    messagingSenderId: '104865530314',
    projectId: 'flash-chatt-c221b',
    authDomain: 'flash-chatt-c221b.firebaseapp.com',
    storageBucket: 'flash-chatt-c221b.firebasestorage.app',
    measurementId: 'G-9LYMXMFJX8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtM0Jddb-4Ctl_CQTi1hqBLDBpilq6StA',
    appId: '1:104865530314:android:53773ac09aa6a1e3294f33',
    messagingSenderId: '104865530314',
    projectId: 'flash-chatt-c221b',
    storageBucket: 'flash-chatt-c221b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7k3JMAYC_SWZRAURhAJbYLBP8-ZBzMiY',
    appId: '1:104865530314:ios:9253d2ace4e401bb294f33',
    messagingSenderId: '104865530314',
    projectId: 'flash-chatt-c221b',
    storageBucket: 'flash-chatt-c221b.firebasestorage.app',
    iosBundleId: 'com.example.cloudChatFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7k3JMAYC_SWZRAURhAJbYLBP8-ZBzMiY',
    appId: '1:104865530314:ios:9253d2ace4e401bb294f33',
    messagingSenderId: '104865530314',
    projectId: 'flash-chatt-c221b',
    storageBucket: 'flash-chatt-c221b.firebasestorage.app',
    iosBundleId: 'com.example.cloudChatFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALGmkHNr4R7meFSZio64T7JIwsaxyzDlk',
    appId: '1:104865530314:web:6fc456a219638523294f33',
    messagingSenderId: '104865530314',
    projectId: 'flash-chatt-c221b',
    authDomain: 'flash-chatt-c221b.firebaseapp.com',
    storageBucket: 'flash-chatt-c221b.firebasestorage.app',
    measurementId: 'G-RVGSDQ0X4N',
  );
}
